version: "3.8"
services:
  mongodb:
    image : davybello/mongo-replica-set:5.0.12
    container_name: mongodb
    volumes:
      - "./docker/.data/mongo1:/var/lib/mongo1"
      - "./docker/.data/mongo2:/var/lib/mongo2"
      - "./docker/.data/mongo3:/var/lib/mongo3"
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    networks: 
      - mongodbNetwork
  react-app:
    image: react-phone
    build: 
      context: .
    container_name: react-phone
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    # environment:
    #   - DATABASE_URL="mongodb://mongodb:27017/react-phone"
    networks: 
      - mongodbNetwork
networks: 
  mongodbNetwork:
    driver: bridge